### ISSUE TITLE
[FIX] 심사 대응

### ISSUE THREAD

**Issue by JYPjoy** [bside-tinkerbell/Waving-iOS#99]
## 📝 Issue Summary

- 앱스토어 리뷰에서 **전화번호** 인증과 **둘러보기** 기능을 추가하라고 함

>  Hello,
> 
> Thank you for your efforts to follow our guidelines. There are still some issues that need your attention.
> 
> If you have any questions, we are here to help. Reply to this message in App Store Connect and let us know. 
> 
> Guideline 2.1 - Information Needed
> 
> We have started the review of your app, but in addition to the demo account username and password you provided, we need an phone number and authentication code to complete the registration process.
> 
> App Review conducts a full review of all apps submitted to the App Store, including content and services that require authentication codes to access.
> 
> Next Steps
> 
> In order for us to proceed with the review of your app, you will need to provide an authentication code. Please respond to this message with the code. 
> 
> If you are unable to provide a code by reply, you can arrange for an Apple representative to call you to obtain the code. [Follow this link to request a call using our online form.](https://developer.apple.com/contact/request/app-review/call/?teamId=XQ24HP64B3&appId=6451205413&platform=ios)
> 
> Before requesting a call, confirm the phone number listed in the App Review Information section of this app's Version Information page in [App Store Connect](https://appstoreconnect.apple.com/) is up-to-date.
> 
> You may also include a demonstration mode that exhibits your app’s full features and functionality. We do not accept demo videos to show your app in use for this issue.
> 
> Resources 
> 
> Learn how to [share information with App Review when submitting your app for review](https://developer.apple.com/help/app-store-connect/reference/app-review-information/).
> 
> Guideline 5.1.1 - Legal - Privacy - Data Collection and Storage
> 
> We noticed that your app requires users to register or log in to access features that are not account based.
> 
> Apps may not require users to enter personal information to function, except when directly relevant to the core functionality of the app or required by law. For example, an e-commerce app should let users browse store offerings and other features that are not account based before being asked to register, or a restaurant app should allow users to explore the menu before placing an order. Registration must then only be required for account-specific features, such as saving items for future reference or placing an order.
> 
> Next Steps
> 
> To resolve this issue, please revise your app to let users freely access your app’s features that are not account based. 
> 
> Resources 
> 
> - Watch a video from App Store Review with [tips for doing more for users with less data](https://developer.apple.com/go/?id=ar-tips-3). 
> - See [guideline 5.1.1(v) - Account Sign-In](https://developer.apple.com/app-store/review/guidelines/#data-collection-and-storage) to learn more about our requirements for apps with account-based content and features.
> Please see attached screenshot for details.

<br/>

## ✅ TO - DO

- [ ] 회원 가입 과정 제대로 되는지 체크하기: 전화번호 인증 과정 제외하기
- [ ] 둘러보기 기능 추가
- [ ] 홈 화면 등 다른 화면에서 클릭 시 로그인을 해야 볼 수 있어요 라는 토스트 메시지 나오도록 추가
- [ ] 앱 회신에 둘러보기 기능만으로는 보는데 한계가 있을 거라 이야기하기

**Comment by choiapril6** [comment]
전화번호 인증과정 제외하려면
- [ ] 가입할 때 서버에서 cellphone 파라미터를 필수로 체크하지 않도록 수정 요청해야함 (원우님)
- [ ] 앱에서는 해당과정 생략하도록 수정해야함
